<a href="https://colab.research.google.com/github/antonellafontanetto/DataScience-Entregas/blob/main/N5_Curso.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Programa Ingenias+ Data Science

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


In [ ]:
#Importar numpy
import numpy as np

In [ ]:
#Ejercicio1 Crear un arreglo de ceros de longitud 12

In [ ]:
array_12=np.zeros(12) #doy nombre al array
print(array_12) #luego lo imprimo
len (array_12) #la función len me permite la longitud


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


12

**1.1** Voy a crear un arreglo de ceros de longitud 10, a modo de otro ejemplo ;)

In [ ]:
import numpy as np


In [ ]:
array_10=np.zeros(10) #acá creo la variable
print(array_10) #luego imprimo la variable
len (array_10) #la función len me permite obtener la longitud de mi array
print (np.zeros(10,dtype=int)) #esta función va a permitir que la lista venga en formato de número entero y no así como decimales

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]


In [ ]:
#ejercicio2 Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5

In [ ]:
array_diez=np.zeros(10) #acá creo el array con una longitud de 10
array_diez[5]=10 #en esta instancia determino que en la posición 5 partiendo de la lista 0,1,2,3,4, y 5 se incorpore el número 10
array_diez[7]=8 #acá replico el mismo ejercicio anterior pero incorporando el número 8 en la posición 7
print(array_diez)
len (array_diez)

[ 0.  0.  0.  0.  0. 10.  0.  8.  0.  0.]


10

In [ ]:
#ejercicio3 Crear un arreglo que tenga los números del 10 al 49

In [ ]:
array_10_49=np.arange(10,50) #determina el array con los valores del 10 al n-1, es por ello que muestra como último valor el 49
print(array_10_49)
len (array_10_49)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


40

In [ ]:
#ejercicio4 Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8

In [ ]:
array_8_10=np.arange(9).reshape(3,3) #en esta instancia se creó el array determinando con la función arange que contenga n-1 valores y con la función reshape cambia la forma del array en este caso da una matriz de 3x3
print(array_8_10)
print(array_8_10.ndim) #en esta ocasión utilice .ndim para pedir la dimensión del array
array_8_10=np.resize(array_8_10,(6)) #resize me permitió recortar el array inicial con n-1 elementos y dejarlo en formato de lista
print(array_8_10)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
2
[0 1 2 3 4 5]


In [ ]:
#ejercicio5 Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza

In [ ]:
array_100=np.random.rand(100) #en esta instancia creamos un array que contenga n-1 elementos pero con datos aleatorios
print(array_100)

[7.23445630e-01 3.92379718e-01 3.30878727e-01 3.34280702e-01
 3.54376212e-01 4.87056862e-01 6.86772173e-01 6.48278804e-01
 1.84352706e-01 4.05904753e-01 8.93622177e-01 3.26285221e-01
 6.37909334e-01 9.55672314e-01 8.32563527e-01 5.18709914e-01
 6.12002814e-01 9.72170694e-01 3.81703933e-01 5.80158555e-01
 1.18098750e-01 9.35833057e-01 6.69252616e-01 1.48460570e-01
 8.35325762e-01 1.03547818e-01 4.40733192e-01 3.94230992e-01
 4.71664210e-01 1.34596325e-01 7.83209630e-01 6.61250028e-01
 2.26245033e-01 1.07533642e-01 4.68687976e-01 7.63235936e-01
 2.22542489e-01 7.16632321e-02 7.17168320e-04 1.45315842e-01
 2.05117493e-01 6.60988086e-01 5.84978133e-01 4.09729932e-01
 5.15092664e-01 9.53926335e-01 9.19882712e-01 5.96716904e-01
 2.72577520e-01 5.96044833e-01 3.63495352e-01 3.66081806e-01
 8.52823292e-01 1.72600758e-01 9.21972767e-01 8.16694060e-01
 9.11632308e-02 4.55539551e-01 4.31477152e-01 2.80428564e-01
 6.64542464e-01 1.82505671e-01 4.16042961e-01 7.66060765e-01
 9.52590682e-01 2.255341

In [ ]:
array_media=np.mean(array_100) #en este caso calculamos la media aritmetica de todos los valores aleatorios que contiene mi array
print(array_media)
array_varianza=np.var(array_100) #con np.var podemos calcular la varianza que es la media de los cuadrados de las desviaciones sobre la media
print(array_varianza)
array_dstandar=np.std(array_100) #en este caso incorpore la función para calcular la desviación standar que es una medida de dispersión de los datos en relación a la media
print(array_dstandar)

0.4814201851165778
0.08308739506875785
0.28824884226785347


In [ ]:
#ejercicio6 Calcular la media de un arreglo usando np.sum

In [ ]:
listamedia=[10,20,30,40,50,60,70] #creo una lista
array_m=np.array(listamedia)
print(array_m)
suma=np.sum(array_m) #aplique la función suma para el array creado
print(suma)
media=np.mean(array_m) #aplique la función media para el array creado
print(media)
array_msum=np.sum(array_m)/[len(array_m)] #en este caso se utiliza la función suma para calcular la media aritmetica
print(array_msum)

[10 20 30 40 50 60 70]
280
40.0
[40.]


In [ ]:
#ejercicio 7 Calcular la varianza de un arreglo usando np.sum y np.mean

In [ ]:
lista1=[100,120,250,500,700,250] #creo la lista
array_5=np.array(lista1)
print (array_5)
len(array_5)
print (np.var(array_5)) #calculo la varianza
array_suma=np.sum(array_5) #aplico función suma al array creado
print (array_suma)
array_media=np.mean(array_5) #aplico la función media al array creado
print (array_media)
Diferencia=array_5-array_media #calculo la diferencia entre el array y la media
print (Diferencia)
Dif_cuadrado=Diferencia**2 #elevo la diferencia al cuadrado
print(Dif_cuadrado)
suma_cuadrado=np.sum(Dif_cuadrado) #realizo la suma de la diferencia al cuadrado
print(suma_cuadrado)
varianza=suma_cuadrado/len(array_5) #calculo la varianza como el cociente entre la suma al cuadrado dividido por la longitud de mi array
print(varianza)
array_5_varianza=np.sum((array_5-np.mean(array_5))**2)/[len(array_5)]
print(array_5_varianza)

[100 120 250 500 700 250]
45833.333333333336
1920
320.0
[-220. -200.  -70.  180.  380.  -70.]
[ 48400.  40000.   4900.  32400. 144400.   4900.]
275000.0
45833.333333333336
[45833.33333333]


In [ ]:
#Ejercicio8
#Crear un array de números aleatorios usando np.random.randn.

In [ ]:
#Crear un array de números aleatorios usando np.random.randn.
array_aletorio=np.random.rand(15) #la función np.random.randn crea una lista de 15 números aleatorios
print(array_aletorio)

[0.66202087 0.38242205 0.96638772 0.98863615 0.68910817 0.4043012
 0.64983896 0.06110275 0.62030889 0.69191956 0.86496484 0.12010734
 0.71284706 0.57183617 0.96245412]
